import { create } from 'zustand';
import { GoogleGenAI } from '@google/genai';
import JSZip from 'jszip';

export type NodeStatus = 'idle' | 'running' | 'success' | 'error';
export type FlowState = 'idle' | 'running' | 'paused' | 'completed' | 'error';
export type DeviceMode = 'desktop' | 'tablet' | 'mobile';

export interface Artifact {
  id: string;
  name: string;
  type: 'json' | 'markdown' | 'folder' | 'zip' | 'html';
  time: string;
  status: 'pending' | 'success' | 'error';
  content?: string;
}

export interface ComponentMorsel {
  id: string;
  name: string;
  type: string;
  weight: string;
  profile: string;
  locked: boolean;
}

interface FlowStore {
  flowState: FlowState;
  activeNode: string | null;
  nodeStatuses: Record<string, NodeStatus>;
  artifacts: Artifact[];
  messages: { role: 'user' | 'model' | 'system', text: string }[];
  previewCode: string | null;
  blueprint: any | null;
  deviceMode: DeviceMode;
  components: ComponentMorsel[];

  setDeviceMode: (mode: DeviceMode) => void;
  startFlow: (intent: string) => Promise<void>;
  pauseFlow: () => void;
  stopFlow: () => void;
  setNodeStatus: (nodeId: string, status: NodeStatus) => void;
  addArtifact: (artifact: Artifact) => void;
  addMessage: (msg: { role: 'user' | 'model' | 'system', text: string }) => void;
  resetFlow: () => void;
  exportBuild: () => Promise<void>;
}

const initialNodeStatuses: Record<string, NodeStatus> = {
  '1': 'idle', '2': 'idle', '3': 'idle', '4': 'idle', '5': 'idle',
  '6': 'idle', '7': 'idle', '8': 'idle', '9': 'idle'
};

export const useFlowStore = create<FlowStore>((set, get) => ({
  flowState: 'idle',
  activeNode: null,
  nodeStatuses: { ...initialNodeStatuses },
  artifacts: [],
  messages: [
    { role: 'system', text: 'Cinematic Studio OS initialized. Ready for creative intent.' }
  ],
  previewCode: null,
  blueprint: null,
  deviceMode: 'desktop',
  components: [],

  setDeviceMode: (mode) => set({ deviceMode: mode }),

  setNodeStatus: (nodeId, status) => set((state) => ({
    nodeStatuses: { ...state.nodeStatuses, [nodeId]: status }
  })),

  addArtifact: (artifact) => set((state) => ({
    artifacts: [artifact, ...state.artifacts]
  })),

  addMessage: (msg) => set((state) => ({
    messages: [...state.messages, msg]
  })),

  pauseFlow: () => set({ flowState: 'paused' }),
  
  stopFlow: () => set({ flowState: 'idle', activeNode: null, nodeStatuses: { ...initialNodeStatuses } }),

  resetFlow: () => set({
    flowState: 'idle',
    activeNode: null,
    nodeStatuses: { ...initialNodeStatuses },
    artifacts: [],
    previewCode: null,
    blueprint: null,
    components: [],
    messages: [{ role: 'system', text: 'Flow reset. Ready for new intent.' }]
  }),

  exportBuild: async () => {
    const { blueprint, previewCode, addMessage } = get();
    if (!previewCode) {
      addMessage({ role: 'system', text: 'Export failed: No preview code available.' });
      return;
    }

    addMessage({ role: 'system', text: 'Packaging export build...' });
    
    try {
      const zip = new JSZip();
      
      // Add files to zip
      zip.file('index.html', previewCode);
      if (blueprint) {
        zip.file('creative-blueprint.json', JSON.stringify(blueprint, null, 2));
      }
      zip.file('README.md', '# Cinematic Studio Export\n\nGenerated by Cinematic Studio OS.\n\nTo view, simply open `index.html` in any modern browser.');

      // Generate zip blob
      const content = await zip.generateAsync({ type: 'blob' });
      
      // Trigger download
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'cinematic-export.zip';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      addMessage({ role: 'system', text: 'Export downloaded successfully.' });
    } catch (error: any) {
      console.error('Export error:', error);
      addMessage({ role: 'system', text: `Export failed: ${error.message}` });
    }
  },

  startFlow: async (intent: string) => {
    const { addMessage, setNodeStatus, addArtifact } = get();
    
    // Reset previous flow state but keep messages
    set({
      flowState: 'running',
      activeNode: '1',
      nodeStatuses: { ...initialNodeStatuses, '1': 'running' },
      previewCode: null,
      blueprint: null,
      components: [],
      artifacts: []
    });

    addMessage({ role: 'user', text: intent });

    try {
      const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
      if (!apiKey) throw new Error('API Key missing');
      const ai = new GoogleGenAI({ apiKey });

      // Node 1: Raw Intent -> Success
      setNodeStatus('1', 'success');
      
      // Node 2 & 3: Intent Analysis & Creative Upgrade
      set({ activeNode: '2' });
      setNodeStatus('2', 'running');
      setNodeStatus('3', 'running');
      
      addMessage({ role: 'system', text: 'Analyzing intent and applying creative upgrade...' });
      
      // Generate Blueprint
      set({ activeNode: '4' });
      setNodeStatus('2', 'success');
      setNodeStatus('3', 'success');
      setNodeStatus('4', 'running');

      const blueprintResponse = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `User intent: ${intent}\n\nCreate a high-end cinematic blueprint for this. Return ONLY a valid JSON object with the following structure: { "aesthetic": "...", "palette": { "primary": "...", "accent": "...", "background": "..." }, "typography": { "headings": "...", "body": "..." }, "animation": "...", "components": [{"name": "...", "type": "Section|Micro-UI|Element", "weight": "High|Medium|Low", "profile": "..."}] }`,
        config: {
          responseMimeType: 'application/json',
        }
      });

      const blueprintText = blueprintResponse.text || '{}';
      const blueprint = JSON.parse(blueprintText);
      set({ blueprint });

      // Extract components for the Morsel Library
      if (blueprint.components && Array.isArray(blueprint.components)) {
        const extractedComponents: ComponentMorsel[] = blueprint.components.map((c: any, i: number) => ({
          id: `comp-${Date.now()}-${i}`,
          name: c.name || 'Unnamed Component',
          type: c.type || 'Component',
          weight: c.weight || 'Medium',
          profile: c.profile || 'Standard',
          locked: false
        }));
        set({ components: extractedComponents });
      }

      addArtifact({
        id: Date.now().toString(),
        name: 'creative-blueprint.json',
        type: 'json',
        time: new Date().toLocaleTimeString(),
        status: 'success',
        content: JSON.stringify(blueprint, null, 2)
      });

      addMessage({ role: 'model', text: `Blueprint generated successfully:\n\`\`\`json\n${JSON.stringify(blueprint, null, 2)}\n\`\`\`` });

      setNodeStatus('4', 'success');

      // Node 5 & 6: Component Graph & Code Gen
      set({ activeNode: '6' });
      setNodeStatus('5', 'success');
      setNodeStatus('6', 'running');

      addMessage({ role: 'system', text: 'Generating high-fidelity code artifacts...' });

      const codeResponse = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `Based on this blueprint: ${JSON.stringify(blueprint)}\n\nGenerate a single HTML file containing a stunning, cinematic landing page. Use Tailwind CSS via CDN (<script src="https://cdn.tailwindcss.com"></script>). Use GSAP for animations (<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>). Include beautiful Unsplash images. Make it look like a high-end studio designed it. Return ONLY the raw HTML code, no markdown formatting, no \`\`\`html tags.`,
      });

      let code = codeResponse.text || '';
      // Clean up markdown if AI included it
      code = code.replace(/^```html\n?/, '').replace(/\n?```$/, '');

      set({ previewCode: code });

      addArtifact({
        id: (Date.now() + 1).toString(),
        name: 'index.html',
        type: 'html',
        time: new Date().toLocaleTimeString(),
        status: 'success',
        content: code
      });

      setNodeStatus('6', 'success');

      // Node 7: QA Audit
      set({ activeNode: '7' });
      setNodeStatus('7', 'running');
      addMessage({ role: 'system', text: 'Running Quality Audit...' });
      
      // Simulate QA Audit checks
      await new Promise(r => setTimeout(r, 1500));
      let qaPassed = true;
      if (!code.includes('gsap')) {
        qaPassed = false;
        addMessage({ role: 'system', text: 'QA Warning: GSAP not detected in output. Animations may be flat.' });
      }
      if (!code.includes('tailwind')) {
        qaPassed = false;
        addMessage({ role: 'system', text: 'QA Warning: Tailwind CSS not detected in output.' });
      }
      
      if (qaPassed) {
        addMessage({ role: 'system', text: 'QA Audit passed: Cinematic quality verified.' });
      }
      setNodeStatus('7', qaPassed ? 'success' : 'error');

      // Node 8: Preview
      set({ activeNode: '8' });
      setNodeStatus('8', 'success');

      addMessage({ role: 'system', text: 'Preview build ready. Rendering in sandbox.' });

      // Node 9: Export
      set({ activeNode: '9' });
      setNodeStatus('9', 'success');
      
      addArtifact({
        id: (Date.now() + 2).toString(),
        name: 'export.zip',
        type: 'zip',
        time: new Date().toLocaleTimeString(),
        status: 'success'
      });

      set({ flowState: 'completed', activeNode: null });

    } catch (error: any) {
      console.error(error);
      addMessage({ role: 'system', text: `Error: ${error.message}` });
      set({ flowState: 'error' });
      if (get().activeNode) {
        setNodeStatus(get().activeNode as string, 'error');
      }
    }
  }
}));
